eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: EMPLOYEE
          uri: lb://EMPLOYEE
          predicates:
            - Path=/employees/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: EMPLOYEE-SERVICE
                fallbackUri: forward:/employeeServiceFallback

        - id: ADDRESS
          uri: lb://ADDRESS
          predicates:
            - Path=/addresses/**
          filters:
            - AuthFilter
            - name: CircuitBreaker
              args:
                name: ADDRESS-SERVICE
                fallbackUri: forward:/addressServiceFallback

        - id: AUTH
          uri: lb://AUTH
          predicates:
            - Path=/auth/**


resilience4j:
  timelimiter:
    instances:
      EMPLOYEE-SERVICE:
        timeoutDuration: 19s
      ADDRESS-SERVICE:
        timeoutDuration: 15s
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 25s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
